# Copyright (c) 2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

metadata:
    format: Lava-Test Test Definition 1.0
    name: Create Python environment including pytest into the LXC container.
    description: Python Environment Creation.

parameters:
    # virtual_env specifies the name of the virtual environment
    #
    virtual_env:

    # pytest_download specifies the location to download the pytest files
    #
    host_download_dir:

run:
    steps:
        # Create and activate the python venv
        - python3 -m venv $virtual_env
        - . $virtual_env/bin/activate

        # Upgrade version of pip3
        - pip3 install --upgrade pip

        # Download pytest.
        # Do this in two stages so the files are available for installing on the DUT as well
        #
        - pip3 download -d $host_download_dir pytest

        # Install pytest
        - pip3 install --no-index --find-links=$host_download_dir pytest

        # Install manifest-tool
        - pip3 install manifest-tool
