version: 2

jobs:
  licenses:
    machine: true
    steps:
      - checkout:
          path: repo-under-test
      - run:
          name: Get mbl-tools
          command: git clone https://github.com/ARMmbed/mbl-tools
      - run:
          name: Licensing check
          command: mbl-tools/ci/licensing-check/run-me.sh --no-tty --workdir repo-under-test

  sanity:
    machine: true
    steps:
      - checkout:
          path: repo-under-test
      - run:
          name: Get mbl-tools
          command: git clone https://github.com/ARMmbed/mbl-tools
      - run:
          name: Sanity check
          command: mbl-tools/ci/sanity-check/run-me.sh --no-tty --workdir repo-under-test

  clang-tidy:
    docker:
      - image: ubuntu
    steps:
      - checkout:
          path: repo-under-test
      - run:
          name: Install env
          command: apt-get update && apt-get install -y python3 && apt-get install -y clang-tidy && apt-get install -y cmake
      - run:
          name: Install libs
          command: apt-get install -y libsystemd-dev
      - run:
          name: Run clang tidy
          command: repo-under-test/ci/clang-tidy/run-clang-tidy.py

workflows:
  version: 2

  checkers:
    jobs:
      - licenses
      - sanity
      - clang-tidy
