version: 2

jobs:
  licenses:
    machine: true
    steps:
      - checkout:
          path: repo-under-test
      - run:
          name: Get mbl-tools
          command: git clone https://github.com/ARMmbed/mbl-tools
      - run:
          name: Licensing check
          command: mbl-tools/ci/licensing-check/run-me.sh --no-tty --workdir repo-under-test

  sanity:
    machine: true
    steps:
      - checkout:
          path: repo-under-test
      - run:
          name: Get mbl-tools
          command: git clone https://github.com/ARMmbed/mbl-tools
      - run:
          name: Sanity check
          command: mbl-tools/ci/sanity-check/run-me.sh --no-tty --workdir repo-under-test

  clang-tidy:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout:
          path: repo-under-test
      - run:
          name: Install libs
          command: apt-get install libsystemd-dev && apt-get install clang-tidy
      - run:
          name: Run clang tidy
          command: ci/clang-tidy/run-clang-tidy.py

workflows:
  version: 2

  checkers:
    jobs:
      - licenses
      - sanity
      - clang-tidy
