#!/bin/sh

# Copyright (c) 2018 ARM Ltd.
#
# SPDX-License-Identifier: Apache-2.0

# Redirect stdout and stderr to the log file
name=${0##*/}
exec >>"/var/log/${name}.log" 2>&1
printf "%s: %s\n" "$(date '+%FT%T%z')" "Starting ${name}"

set -x

wait_for_app_update_file() {
    set +x
    echo "Waiting for app update"
    while ! [ -e "/mnt/cache/do_app_update" ]; do
        sleep 1
    done
    echo "App update starting"
    set -x
    rm "/mnt/cache/do_app_update"
}

update_apps() {
    mbl-app-update-manager --install-packages "$(cat /mnt/cache/firmware_path)"
    printf "%s\n" "$?" > /mnt/cache/app_update_rc
    rm /mnt/cache/firmware_path
    touch "/mnt/cache/done_app_update"
}

while true; do
    wait_for_app_update_file
    update_apps
done

# Should never get here
exit 1
